version: "3.9"
services:
  mobilecap:
    image: ${OPENCAP_IMAGE_NAME}
    volumes:
      - data:/data
    env_file:
      - ../.env
    environment:
      - DOCKERCOMPOSE=1
      - NVIDIA_VISIBLE_DEVICES=${INSTANCE_ID}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    cpuset: "${CPU_SET}"
  openpose:
    image: ${OPENPOSE_IMAGE_NAME}
    volumes:
      - data:/openpose/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=${INSTANCE_ID}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    cpuset: "${CPU_SET}"
  mmpose:
    image: ${MMPOSE_IMAGE_NAME}
    volumes:
      - data:/mmpose/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=${INSTANCE_ID}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    cpuset: "${CPU_SET}"

volumes:
  data: {}
