version: "3.9"
services:
  mobilecap:
    image: 660440363484.dkr.ecr.us-west-2.amazonaws.com/opencap/opencap
    volumes:
      - data:/data
    env_file:
      - ../.env
    environment:
      - DOCKERCOMPOSE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  openpose:
    image: 660440363484.dkr.ecr.us-west-2.amazonaws.com/opencap/openpose
    volumes:
      - data:/openpose/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  mmpose:
    image: 660440363484.dkr.ecr.us-west-2.amazonaws.com/opencap/mmpose
    volumes:
      - data:/mmpose/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  data: {}
